package uk.ac.standrews.cs.sos.impl.manifests;

import uk.ac.standrews.cs.IGUID;
import uk.ac.standrews.cs.sos.exceptions.crypto.EncryptionException;
import uk.ac.standrews.cs.sos.exceptions.manifest.ManifestNotMadeException;
import uk.ac.standrews.cs.sos.exceptions.manifest.ManifestVerificationException;
import uk.ac.standrews.cs.sos.model.ManifestType;
import uk.ac.standrews.cs.sos.model.Role;
import uk.ac.standrews.cs.utilities.crypto.CryptoException;

/**
 * Abstract class for all manifests that support signatures.
 *
 * @author Simone I. Conte "sic2@st-andrews.ac.uk"
 */
public abstract class SignedManifest extends BasicManifest {

    protected final Role signer;
    protected String signature;

    /**
     * Constructor for a signed manifest.
     *
     * @param signer for this manifest
     * @param manifestType the type of manifest
     */
    protected SignedManifest(Role signer, ManifestType manifestType) {
        super(manifestType);

        this.signer = signer;
    }

    /**
     * Get the signer identifier used for this manifest
     *
     * @return the GUID for the signer
     */
    public IGUID getSigner() {
        return this.signer.guid();
    }

    /**
     * Gets the signature of this manifest.
     *
     * @return signature of this manifest.
     */
    public String getSignature() {
        return this.signature;
    }

    /**
     * Verify this manifest against the given identity
     *
     * @param role used to satisfied the signature
     * @return true if the signature was generated by that role
     * @throws ManifestVerificationException if the verification could not be carried out
     */
    @Override
    public boolean verifySignature(Role role) throws ManifestVerificationException {

        boolean success;
        try {
            String manifestToSign = getManifestToSign();
            success = role.verify(manifestToSign, signature);
        } catch (CryptoException e) {
            throw new ManifestVerificationException("Unable to decrypt identity", e);
        }

        return success;
    }

    /**
     * Generate the signature for this manifest
     *
     * @return the signature for this manifest
     * @throws ManifestNotMadeException if the manifest could not signed
     */
    protected String makeSignature() throws ManifestNotMadeException {
        String signature;
        try {
            String manifestToSign = getManifestToSign();
            signature = generateSignature(manifestToSign);
        } catch (Exception e) {
            throw new ManifestNotMadeException("Manifest could not be signed", e);
        }
        return signature;
    }

    /**
     * Get the manifest sections to sign
     *
     * @return manifest sections to sign as a string
     */
    protected abstract String getManifestToSign();

    /**
     * Generates the signature for this manifest.
     *
     * @return signature of this manifest.
     */
    protected abstract String generateSignature(String toSign) throws EncryptionException;
}
