package uk.ac.standrews.cs.sos.model;

import uk.ac.standrews.cs.guid.IGUID;
import uk.ac.standrews.cs.sos.exceptions.crypto.SignatureException;

/**
 * @author Simone I. Conte "sic2@st-andrews.ac.uk"
 */
public interface SignedManifest extends Manifest {

    /**
     * Get the signer identifier used for this manifest
     *
     * @return the GUID for the signer
     */
    IGUID getSigner();

    /**
     * Gets the signature of this manifest.
     *
     * @return signature of this manifest.
     */
    String getSignature();

    /**
     * Verify this manifest against the given identity
     *
     * @param role used to satisfied the signature
     * @return true if the signature was generated by that role
     * @throws SignatureException if the verification could not be carried out
     */
    boolean verifySignature(Role role) throws SignatureException;
}
